  File "exceptionQuine.py", line 1
    File "exceptionQuine.py", line 1
    ^
IndentationError: unexpected indent
